### ISSUE TITLE
choose journal

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-paper#1]
I think we want something that permits a short-length format?

**Comment by apragsdale** [comment]
Just to list a few options:

- MBE has Brief Communications that are geared toward software releases
- Similarly, Genetics has Methods, Technology, and Resources that can be "Communications" length
- Would Bioinformatics be appropriate? Don't have any experience with submitting there..

**Comment by jeromekelleher** [comment]
I'm not sure Bioinformatics would be good place for this, we'd want to target a more "genetics" audience rather than general bioinfo.
