### ISSUE TITLE
Discuss relationship to coasim

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-paper#11]
The Guile description of population structure used in coasim looks quite similar to what we've done. We should mention this:

https://link.springer.com/article/10.1186/1471-2105-6-252

**Comment by grahamgower** [comment]
Ah, interesting! The code survives here: https://github.com/mailund/CoaSim

**Comment by jeromekelleher** [comment]
Just something to mention in the discussion - it's still tied to a particular programming language, so doesn't meet the "declarative" requirement.

**Comment by molpopgen** [comment]
I seem to remember some other tools in this vein.  One is [PopPlanner](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4407479/).

**Comment by grahamgower** [comment]
There's a PopPlanner jar file here: https://www.mabs.at/ewing/msms/popplanner.shtml, although when I tried to run it I just got a blank window. Not clear what java version is required (I tried openjdk 15).

**Comment by grahamgower** [comment]
Ah, I got it to work by exporting `_JAVA_AWT_WM_NONREPARENTING=1`. Java makes assumptions which are not true of my window manager.

**Comment by grahamgower** [comment]
Another graphical tool that has disappeared from the web: modeler4simcoal2
https://academic.oup.com/bioinformatics/article/23/14/1848/189124
http://web.archive.org/web/20130312135726/http://popgen.net/soft/m4s2

**Comment by jeromekelleher** [comment]
Cool - good to mention these in the discussion.l

**Comment by jeromekelleher** [comment]
I think these have all gone in, closing.
