### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-paper#13]
The current draft in #12 

- Demes: a specification for interchanging complex demography

Previously we had:

- demes: a pain-free specification for complex demography
 

I'm not sure that "interchanging" will mean that much to a biological audience, so maybe we want to get the word "software" in there somewhere.

Thoughts?

**Comment by grahamgower** [comment]
How about: "Demes: a standard format for demographic models"

**Comment by jeromekelleher** [comment]
This is done I think, closing
