### ISSUE TITLE
include small example analysis?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-paper#2]
Maybe we could take a simple demographic model and reinfer some params with an ABC?

**Comment by jeromekelleher** [comment]
Hmmm - why? I'm not sure what this would demonstrate - I don't think it would prove any points about expressiveness.

**Comment by apragsdale** [comment]
I'm also not sure what this would show, and would likely bump us out of "brief communication" territory.

I think it could be useful to have a short tutorial on outputting sets of ABC results, but that is probably best to include in a Tutorial or Usage Examples section in the demes docs?

**Comment by grahamgower** [comment]
I thought that including an analysis was briefly mentioned on the call, in the context of targeting certain journals? Happy to close this though. Certainly I'd prefer to avoid if possible.

**Comment by jeromekelleher** [comment]
Well we *could* illustrate the idea that we can effectively sample from the posterior, and show that the size resulting ``tar.gz`` is small. I don't think there's any point in getting in to doing any actual analysis, though.
