### ISSUE TITLE
Build broken by JupyterBook update?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-paper#22]
Looks like I broke a bunch of stuff with the latest change @grahamgower  - I assume this is to do with the new version of JupyterBook?  We're seeing a lot of stuff like ``{{ example.replace(“LABEL”, “01”) }}`` in the final docs.

**Comment by jeromekelleher** [comment]
Dammit, wrong repo.

**Comment by molpopgen** [comment]
> Dammit, wrong repo.

I thought you were embarking in a bold new adventure for a second....
