### ISSUE TITLE
Cite the original papers introducing the term "deme"?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-paper#25]
We're using the word "deme" to mean a grouping of individuals that is convenient for modelling. I think this is quite consistent with the term's original use, although it was also intended to encompass a range of more specific terms (and used as a suffix).

[Gilmour & Gregor, 1939](https://www.nature.com/articles/144333a0)
> Deme: any assemblage of taxonomically closely related individuals.

[Gilmour & Heslop-Harrison, 1955](https://link.springer.com/article/10.1007/BF01664158)
> The essence of the deme terminology is the construction of a series
of category-terms by the addition of one or more virtually self-explanatory
prefixes to the "neutral" suffix "-deme". The suffix "-deme"
was originally suggested (GILMOUR and GREGOR, 1939) for use in
connexion with "the experimental delimination of botanical groups",
and was defined as "any assemblage of taxonomically closely related
individuals"; certain prefixes were also proposed, forming category
terms for use in such experimental delimitation.
With the slightly modified definition of deme proposed in the present
paper, in which the limitation of "closely related" is removed, the
scope of the term could obviously be enlarged, by the use of appropriate
prefixes, to provide terminologies of the widest possible application, covering,
in fact, any type of attribute of living things that might be desired.

**Comment by jeromekelleher** [comment]
Sure, can't have too many refs IMO!

**Comment by apragsdale** [comment]
Closing, as these are now included.
