### ISSUE TITLE
Make figure 1 buildable from the Makefile

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-paper#43]
This shouldn't be too hard. The missing piece is the source file from which `fig/minted-snippet.png` is generated. Could you commit this file please @apragsdale, and I can take care of the buildy bits.

**Comment by apragsdale** [comment]
I can commit those, yes. There may be a more automated way to do it, but I built a tex document with the minted code and then cropped it by hand to include in the figure panel as an imported image. You might find a more automated way to handle that.

**Comment by jeromekelleher** [comment]
Just drop it in and commit would be my vote
