### ISSUE TITLE
non-paper milestones to complete before submitting the paper

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-paper#47]
I think it would be good to tag version 1 (or a beta thereof) of the spec before submitting the manuscript. Are there other things folks would like to have in place before submission?

**Comment by apragsdale** [comment]
I think a tag that corresponds to the biorxiv version makes sense. I don't know if we want to potentially paint ourselves into a corner before getting reviews back and publishing, as there may be minor changes we want to make during revisions. So maybe a beta?

**Comment by jeromekelleher** [comment]
Done I think - closing.

**Comment by jeromekelleher** [comment]
Actually, not sure we did. Reopening for now: https://github.com/popsim-consortium/demes-spec/issues/136

**Comment by grahamgower** [comment]
Now it's done.
