### ISSUE TITLE
Discussion of complex life history parameters

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-paper#5]
A deme is defined as a population that can be described by a fixed set of population parameters. We are concerned with parameters that are not about the genome itself, but rather population processes. Currently we have the very simple idea of population size, plus the ``selfing_rate`` and ``cloning_rate`` parameters (which, AFAIK, no programs are currently implementing). Are these parameters sufficient to describe all of the different life history parameters that we might want to capture? If not, what extra parameters would we require to do this? Should we go ahead and define all these parameters in the spec, or just lay out a path for future extensions that would enable us to support programs working with these systems as they come along?

What about things like haplodiploidy? Could we describe the life-history processes of, say, the malaria parasite in Demes? Should this type of complexity be in scope? If not, what is the limit of what we *should* be concerned with?

These issues of the scope of the Demes standard should be dealt with in the paper - @MattHartfield has been working with funky plant breeding systems for a while, and has agreed to think about this and write it up.

**Comment by MattHartfield** [comment]
Hi @jeromekelleher, thanks for the summary. And hello to everyone else, I'm excited to be involved!

I'll have a think about population vs deme-specific parameters, especially in relation to other reproductive modes. I did touch on this issue in my 2016 paper (https://www.genetics.org/content/202/1/297.abstract), so I've some maths to hand that I can use for these investigations. I suspect that there's areas of parameter space where the effect of facultative sex and/or partial selfing can be collapsed into the deme-specific parameters, but these simplifications might only be possible when assuming similar rates of sex/outcrossing per deme. I'll also think about if complex demographic histories can also be approximated by simpler models.

**Comment by apragsdale** [comment]
Thanks @MattHartfield (and welcome)! I think it's safe to say that `selfing_rate` and `cloning_rate` are not enough to describe all life histories - for example, should we have a field for the offspring distribution? Poisson is the standard in simulators, but there are plenty of species for which that's a bad approximation. Not to mention non-discrete generations or spatial structure..

> which, AFAIK, no programs are currently implementing

I have used the selfing rate in `fwdpy11`, which I believe allows for different rates in different demes (I assume slim lets you do something similar, but not sure). 

I think at first it's reasonable to not expect to cover every life history in the first release that someone _might_ want to simulate, but instead include those cloning and selfing rate examples to guide how to include other models in the specification and fit them into future versions, as demanded?

**Comment by MattHartfield** [comment]
Hi @apragsdale, your suggestions sound good for a first attempt. I especially want to focus on cases where complicated demographies can be (realistically) approximated using simpler coalescent models, to see if a wider array of cases can be covered using the simplest options.

With regards to simulations with different selfing rates and cloning rates, here's my understanding:
- SLiM has options to set per-population selfing and cloning rates (see 'setSelfingRate' and 'setCloningRate' commands).
- My FacSex coalescent simulation program (https://github.com/MattHartfield/FacSexCoalescent) has options to set per-deme rates of sex, which can also change over time.

**Comment by jeromekelleher** [comment]
I agree we don't want to try to be exhaustive in the first release of the spec, and ``selfing_rate``/``cloning_rate`` is good there. What we want here for the paper is a paragraph "looking ahead" to how the spec could be extended to include more complex life history traits. So, a sort of mini-review of what people have done in this space simulation/inference-wise plus a discussion of what sort of parameters we might add to the spec in future to accommodate extra things.
