### ISSUE TITLE
Size changes during epochs, discuss explicitly?

### ISSUE THREAD

**Issue by RyanGutenkunst** [popsim-consortium/demes-paper#55]
The paper says that "Each epoch specifies the population size over that interval, which can be a constant value or function defined by start and end sizes that must remain positive." Figure 1A suggests that the default function is exponential, but this isn't explicitly mentioned anywhere I can find. I did see in the Python API docs that the current options are constant, linear, or exponential.

1) I'd like the default behavior to be explicit somewhere in the manuscript. I know the implementation is the ultimate arbitrator, but having to run the parser to discover this seems a bit much.

2) For my own clarity, the demes specification excludes population size functions that depend on parameters, correct? For example, logistic growth could not be modeled because one would need an r parameter. Just a question, not a stopping issue.

(In my naive days writing dadi long ago, I was so happy it was flexible enough to include any pop size function, before realizing population geneticists only care about exponentials and constants!)

**Comment by molpopgen** [comment]
> 2\. For my own clarity, the demes specification excludes population size functions that depend on parameters, correct? For example, logistic growth could not be modeled because one would need an r parameter. Just a question, not a stopping issue.

In theory, logistic growth could be handled via top-level metadata and the software consuming the graph has to know what to do.

A TODO item in the spec is to convert `size_function` to an enumeration.  Presumably, that enumeration could have room for a field named something like CUSTOM, with the idea that the consumer has to refer to the metadata to learn what to do.

**Comment by molpopgen** [comment]
> 1. I'd like the default behavior to be explicit somewhere in the manuscript. I know the implementation is the ultimate arbitrator, but having to run the parser to discover this seems a bit much.

The others can weigh in, but we've been deferring a lot of this kind of thing to the detailed [spec docs](https://popsim-consortium.github.io/demes-spec-docs/main/specification.html).

**Comment by RyanGutenkunst** [comment]
> The others can weigh in, but we've been deferring a lot of this kind of thing to the detailed [spec docs](https://popsim-consortium.github.io/demes-spec-docs/main/specification.html).

Ah, I hadn't seen that... And it's clear there.
