### ISSUE TITLE
fix tense inconsistencies in the software table

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-paper#57]
Pointed out by @RyanGutenkunst.

**Comment by jeromekelleher** [comment]
I don't see what the problem is immediately - has this been fixed?

**Comment by grahamgower** [comment]
> A Python library for loading, saving, and working with Demes models.

Loading, saving and working are in the present tense.

> Compute expected diversity statistics (SFS, LD) and perform demographic inference using summary statistics

Compute and perform are in the imperative.

Is this what you meant @RyanGutenkunst?

**Comment by RyanGutenkunst** [comment]
Yep, and some entries describe what the tool does without mentioning demes (e.g., GADMA), whereas others are more specific about what they actually do with demes.

**Comment by jeromekelleher** [comment]
I see. My grammar is pretty terrible (clearly!), would you mind fixing it up @RyanGutenkunst?

**Comment by RyanGutenkunst** [comment]
Sure. I think it'd be helpful to specify what these software can do with demes.
@noscode What does GADMA do with demes models? Is it more than drawing of models?
@molpopgen What about fwdpy?
@apragsdale For moments, is it just importing and simulating demes models right now?

Also, I see that the documentation of demes mentions demes-slim, but the repository warns that it is outdated. @grahamgower Do we include it in the table?

**Comment by grahamgower** [comment]
> Also, I see that the documentation of demes mentions demes-slim, but the repository warns that it is outdated. @grahamgower Do we include it in the table?

There are actually only 3 known issues that need to be fixed before it's ready for users, none of which are difficult to resolve. But I don't have a pressing need for demes-slim right now so I haven't gotten around to fixing the issues. Maybe including it in the table would prompt an interested party to step up and help?

**Comment by jeromekelleher** [comment]
Have you talked with Ben Haller about demes-slim @grahamgower?

**Comment by noscode** [comment]
Yes, sure, @RyanGutenkunst, it definitely worth adding. As for GADMA, it provides `demes` descriptions in yaml format and visualization with demesdraw for the inferred demographic histories.

**Comment by apragsdale** [comment]
> @apragsdale For moments, is it just importing and simulating demes models right now?

Moments can import and simulate, but also can specify parameters in a demes file to be optimized, using either the SFS or LD stats, which will update and output the optimized model in demes format. It works pretty well, but I might do some tweaking to the interface still.

**Comment by grahamgower** [comment]
> Have you talked with Ben Haller about demes-slim @grahamgower?

Yeah, maybe mid last year sometime. I recall he took a brief look at it.

**Comment by RyanGutenkunst** [comment]
> Moments can import and simulate, but also can specify parameters in a demes file to be optimized, using either the SFS or LD stats, which will update and output the optimized model in demes format.

Woah! I recall advocating for this a while ago, but it not getting very far as a formal spec. I should get Travis inspired to port this to dadi. :-)

**Comment by RyanGutenkunst** [comment]
> Maybe including it in the table would prompt an interested party to step up and help?

Sounds like reason enough to include it. I'll add it.

**Comment by apragsdale** [comment]
> > Moments can import and simulate, but also can specify parameters in a demes file to be optimized, using either the SFS or LD stats, which will update and output the optimized model in demes format.
> 
> Woah! I recall advocating for this a while ago, but it not getting very far as a formal spec. I should get Travis inspired to port this to dadi. :-)

It's definitely a work in progress! I'd be happy to work together to smooth it out and improve the design of telling the optimizer which parameters to fit. For now, there are some rough docs/examples here, if you or Travis want to take a look: https://moments.readthedocs.io/en/main/extensions/demes.html#using-demes-to-infer-demography

**Comment by molpopgen** [comment]
fwdpy11 uses demes as the "official" method for specifying a demographic model.  Eventually, I want to deprecate use of the low-level Python API, and maybe even completely remove its public visibility, in favor of using `demes.Graph`.

**Comment by RyanGutenkunst** [comment]
@molpopgen @noscode @apragsdale Please review my PR to see whether you like how I've described your software!

**Comment by grahamgower** [comment]
Thanks @RyanGutenkunst, a very nice cleanup to the table.
