### ISSUE TITLE
add acknowledgements section

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-paper#72]
I guess this will be quite sparse, since we forgot it!

**Comment by molpopgen** [comment]
It'll be important for reporting funding sources, if applicable. Definitely need to remember to get it in!

**Comment by RyanGutenkunst** [comment]
Yep, I'll need something like "This work was supported by the National Institute of General Medical Sciences of the National Institutes of Health (R01GM127348 to RNG)."

**Comment by jeromekelleher** [comment]
Yep, good call.

**Comment by jeromekelleher** [comment]
Leaving this open after #74 as others will have grants to ack.

**Comment by jeromekelleher** [comment]
Nice to ack reviewers for helpful suggestions, so leaving this open until that's done.
