### ISSUE TITLE
add demes-julia and demes-rust to software table

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-paper#73]
https://github.com/apragsdale/Demes.jl
https://github.com/molpopgen/demes-rs

**Comment by molpopgen** [comment]
I'm *this* close to saying that the public API for demes-rs has stabilized.  I've done some changes to the Error type since the first release in order to streamline adding a `Builder` type in the future.

**Comment by apragsdale** [comment]
Demes.jl is "functional" but it might be fairly ugly Julia code at the moment... it's also not documented yet. But hopefully I'll get it published soon and start using for some pop gen modeling.
